# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: arithmetic.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'arithmetic.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x61rithmetic.proto\"/\n\x11\x41rithmeticRequest\x12\x0c\n\x04num1\x18\x01 \x01(\x01\x12\x0c\n\x04num2\x18\x02 \x01(\x01\"$\n\x12\x41rithmeticResponse\x12\x0e\n\x06result\x18\x01 \x01(\x01\x32\xd9\x01\n\nArithmetic\x12.\n\x03\x61\x64\x64\x12\x12.ArithmeticRequest\x1a\x13.ArithmeticResponse\x12\x33\n\x08subtract\x12\x12.ArithmeticRequest\x1a\x13.ArithmeticResponse\x12\x33\n\x08multiply\x12\x12.ArithmeticRequest\x1a\x13.ArithmeticResponse\x12\x31\n\x06\x64ivide\x12\x12.ArithmeticRequest\x1a\x13.ArithmeticResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'arithmetic_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ARITHMETICREQUEST']._serialized_start=20
  _globals['_ARITHMETICREQUEST']._serialized_end=67
  _globals['_ARITHMETICRESPONSE']._serialized_start=69
  _globals['_ARITHMETICRESPONSE']._serialized_end=105
  _globals['_ARITHMETIC']._serialized_start=108
  _globals['_ARITHMETIC']._serialized_end=325
# @@protoc_insertion_point(module_scope)
